import Head from "next/head";

const SynerdeaHead = () => {
  return (
    <Head>
      <title>Synerdea</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default SynerdeaHead;
